In [40]:
import pandas as pd
import re
import jieba

In [72]:
news100 = pd.read_excel('appledaily_politinews100.xlsx')
# 文章3，文章29，和文章76含韓國瑜的新聞
koreaLst = [news100['content'][3], news100['content'][29], news100['content'][76]]

In [110]:
# 選擇文章，把文章分成句子
def splitSentences(document):
    #for sent in re.findall(u'[^!?。\.\!\?]+[!?。\.\!\?]?', paragraph, flags=re.U):
    for sent in re.findall(u'[^!?。\!\?]+[!?。\!\?]?', document, flags=re.U):
        yield sent

corpus = []
for doc in koreaLst:
    for sent in list(splitSentences(doc))[:-1]:
        corpus.append(' '.join(jieba.cut(sent)))
corpus

['準 高雄市 長 韓國瑜 的 愛女 韓冰 昨 ( 28 日 ) 受邀 上政論 節目 《 54 新觀點 》 ， 首度 與民進 黨 台北市 議員 王世堅 同台 ， 網友 拱 王世堅 兌現 承諾 跳海 ， 韓冰 不僅 甜 笑 幫忙 緩頰 ， 還邀 他 到 高雄 拚 觀光 ， 讓 王世堅 「 一秒 淪陷 」 靦腆 笑 說 ： 「 如果 我們 高雄 的 民眾 認為 ( 我 去 ) 有用 ， 我 多少 可以 廢物 利用 。',
 '」 \xa0 鄰家 女孩 融化 議會 戰神 的 戰力 ， 對 於 網友 拱 王世堅 兌現 嗆 賭 韓當 選要 跳海 ， 韓冰嬌 柔 說 ： 「 沒關 係 ！ 不用 跳海 ， 可以 來 觀光 旅遊 ， 我 跟 韓總 可以 當導遊 ， 促進 一下 高雄 的 觀光 跟 經濟 ， 可以 不用 跳海 沒關 係 ， 也 不用 跳愛河 ， 這樣 太 危險 了 。',
 '」 \xa0 聽聞 韓冰給 自己 台階下 ， 王世堅 表示 ， 他 跟 韓國瑜 的 共同 點 就是 「 我們 都 比 較 疼 女兒 」 ， 所以 想 跟 韓冰 道歉 ， 「 讓 妳 看到 過去 我 跟 您 父親 這麼 激烈 的 質詢 畫面 ， 真是 很 不好意思 。',
 '」 \xa0 王世堅 解釋 「 跳海 說 」 ， 當時 因 陳 其 邁民調 差得 太離 譜 ， 才 會 在 「 心如 石沉大海 」 的 悲憤 情緒 下 ， 用 跳海 兩個 字 形容 ， 但 他 隔天 隨即 公開 澄清 ， 承諾用 跳海 恭祝 陳 其邁 當選 ， 強調 自己 的 為 人 一向 「 說 到 做到 」 。',
 '\xa0 韓冰則 回應 王世堅 「 不好意思 議員 ， 給你 造成 困擾 」 ， 並 透露 爸爸 其實 很 欣賞 王世堅 ， 「 對 選民 都 很 用心 ， 然後又是 一個 說 到 做到 、 很 說 話 算 話 的 人 」 ， 主持人 陳 斐娟 接話 ： 「 唉 唷 ！ 你 這樣 暗示 他 。',
 '」 韓冰緊 張直 說 ： 「 真的 真的 ( 指 很 守信 ) ！ 喔 不是 ！ 對 不起 ！ 我 不是 在 講那個 。',
 '」 韓冰 自然 不 做作 的 反應 引起 錄影 現場 哄堂大笑 。',
 '\xa0 陳 斐娟 起鬨 向 王世堅 說 ： 「 韓國瑜 很 欣賞 你 ， 你 考慮 一下 ， 去 幫

In [78]:
'''
# 原本文章分成句子
index = 0
#print('標題: ' + '《' + testTitle + '》')
for sentence in corpus:
    print(str(index) + ' ', sentence.replace(' ', '').strip())
    index += 1
'''

"\n# 原本文章分成句子\nindex = 0\n#print('標題: ' + '《' + testTitle + '》')\nfor sentence in corpus:\n    print(str(index) + ' ', sentence.replace(' ', '').strip())\n    index += 1\n"

In [80]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vect = vectorizer.fit_transform(corpus)

In [90]:
vect.toarray()

array([[0, 1, 1, ..., 0, 2, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [91]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(vect)

In [83]:
cs.shape

(22, 22)

In [96]:
from sklearn import cluster
km = cluster.KMeans(n_clusters=3, init='k-means++', random_state=42)
c = km.fit_predict(cs)

In [7]:
import numpy as np
np_corpus = np.array(corpus)
for rec in np_corpus[c==2]:
    print(rec)

NameError: name 'corpus' is not defined

**Testing**

In [31]:
import pandas as pd
import re
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
import numpy as np

In [2]:
news100 = pd.read_excel('appledaily_politinews100.xlsx')
news100.head()

category                                            content  \
0       政治  總統蔡英文卸任民進黨主席，昨在臉書po給黨員的一封信，信中說，民進黨會展開一場轟轟烈烈的檢討...   
1       政治  民進黨這次九合一選舉慘敗，蔡英文辭去黨主席一職，昨公布「給黨員的一封信」，內容提到，最該改變...   
2       政治  2018年地方選舉國民黨拿下空前勝利，執政地區從6縣市竄升為15縣市，昨中常會上國民黨提出選...   
3       政治  準高雄市長韓國瑜的愛女韓冰昨(28日)受邀上政論節目《54新觀點》，首度與民進黨台北市議員王...   
4       政治                             點我直接觀看 被操弄的民調？《蘋果》數據解密   

                          title  
0    蔡英文要轟轟烈烈檢討民進黨　林濁水酸：民主國家沒聽過  
1      他列民進黨10大豬隊友　「不下架將賠上2020」  
2   選戰檢討報告出爐　國民黨：落選者「缺乏對外拓票企圖心」  
3  不用跳愛河！韓冰邀替高雄拚觀光　王世堅靦腆：可以廢物利用  
4      【民調解密3】林佳龍敗在紫爆　盧秀燕跌破眼鏡大勝

In [4]:
# 選擇文章，把文章分成句子
docNum = 31
testDoc = news100['content'][docNum]
testTitle = news100['title'][docNum]

def splitSentences(document):
    #for sent in re.findall(u'[^!?。\.\!\?]+[!?。\.\!\?]?', paragraph, flags=re.U):
    for sent in re.findall(u'[^!?。\!\?]+[!?。\!\?]?', document, flags=re.U):
        yield sent

sentenceDoc = []
for sent in list(splitSentences(testDoc))[:-1]:
    sentenceDoc.append(' '.join(jieba.cut(sent)))

# 原本文章
sentenceDoc

['今年 九 合一 大選 投票 狀況 多 ， 據 了解 ， 中選會 官方 網站 在 投票 日當天 曾 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊 ， 所幸 在 負責 網路 維護 中華電信 應變 下 ， 未進 一步 造成 影響 。',
 '中選會 副 主委 陳 朝 建今 證實 曾 遭駭客 攻擊 ， 不過 計票 網路 是 封閉 系統 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 因此 沒有 任何 影響 ， 境外 網路 干擾 也 並未 影響 投票 進程 。',
 '行政院 發言人 Kolas   Yotaka （ 谷辣斯 ・ 尤達卡 ） 表示 ， 中選會 在 選前 即 做好 縝密 防護 ， 因此 成功 防堵 攻擊 ， 接下 來 將針 對 有形 的 選務如 投票 排隊 問題 ， 以及 無形 的 選務 如資 安防 護進行 檢討 。',
 '不過 ， 投票 日當天 開票 進程 緩慢 ， 台北市 選情 更 創下史 上 第一次 開票 長 達 9 小時 的 紀錄 ， 陳 朝建 說明 ， 開票 時間 長 是 因為 投票 時間 延 後 ， 計票 不受 駭客 影響 ， 開票 也 自然 不受 此 影響 。',
 '據 內部 消息 指出 ， 投票 日當天 曾 出現 從 境外 進行 分散式 阻斷 服務 （ DDoS ） 攻擊 ， 企圖 癱瘓 中選會 網站 ， 不過 在 中華電信 、 中選會 緊急 處理 後 ， 阻斷 來 自國外 異常 流量 ， 在 短 時間 獲得 解決 ， 一般 民眾 並沒有 發現 特殊 異樣 。',
 'NCC 及 中華電信 暫未 對 此 做 進 一步 說明 。',
 '陳 朝建 表示 ， 受 攻擊 的 是 中 選會 官方 網站 ， 當日 開票 的 計票 網路 是 獨立 的 封閉 網路 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 完全 未有 任何 影響 ； 中華電信 團隊 也 是 24 小時 監控 與 防護 作業 ， 也 沒 有 受到 任何 影響 。',
 '陳 朝建 說 ， 受到 攻擊 的 官網 ， 當日 皆 有 隨時 防衛 ， 中華電信 團隊 24 小時 監控 與 防護 作業 ； 故當 日 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊時 ， 在 負責 網路 維護 中華電信 的 緊急 應變 下 ， 並

In [22]:
vect = CountVectorizer()
X = vect.fit_transform(sentenceDoc)

In [23]:
true_k = 3
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)
model.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
    n_clusters=3, n_init=1, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [21]:
print("Top terms per cluster:")
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vect.get_feature_names()
for i in range(true_k):
    print("Cluster %d:" % i,)
    for ind in order_centroids[i, :10]:
        print(' %s' % terms[ind],)
    print()

Top terms per cluster:
Cluster 0:
 防護
 攻擊
 縝密
 成功
 做好
 防堵
 選前
 當天
 中選會
 因此

Cluster 1:
 影響
 開票
 網路
 任何
 受到
 計票
 小時
 朝建
 中華電信
 非公

Cluster 2:
 一步
 中華電信
 中選會
 暫未
 ncc
 阻斷
 投票
 說明
 網站
 所幸



**Instructor Slides Example**

In [96]:
news = pd.read_excel('https://raw.githubusercontent.com/ywchiu/ctbc/master/data/20150628news.xlsx')

In [97]:
corpus = []
titles = []
for rec in news.iterrows():
    corpus.append(' '.join(jieba.cut(rec[1]['description'])))
    titles.append(rec[1]['title'])
corpus

['新北市 八仙 水上 樂園 昨晚 發 生粉 塵 爆炸 ， 新北市 衛生局 統計 到 目前 為止 ， 由 救護車 送 醫再 加上 自行 送醫 的 人數 ， 已經 有 474 人 ， 其中 125 人 重傷 ； 而 新北市 長 朱立倫 昨晚 到 現場 坐鎮 指揮 了解 狀況 ， 並馬上 要求 追究 責任 徹查 ， 並要 八仙 樂園 立刻 關園 停業 ， 八仙 樂園 業者 雖然 表示 活動 是 外包 的 ， 但 也 說 會 配合 暫時 停止 營業 接受 調查 。 警方 今天 凌晨 也 帶 回 五名 相關 人 漏夜 偵訊 ， 包括 現場 呂姓 活動 負責人 、 邱姓 硬體 設備 人員 、 和 廖姓 特效 人員 ， 以及 兩名 在 現場 噴灑 彩色 粉塵 的 2 名 工作 人員 ， 訊後將 依業務 過失 重大 傷害 與 公共 危險 罪嫌 偵辦 ， 統一 移送 士林 地檢署 。 檢警 偵辦 重點 在 於 主辦 單位 辦 這個 活動時 ， 到底 有 沒 有 做好 安全 上 的 防備 ； 據 了解 主辦 人 表示 彩色 派 對 今年 是 第四次 舉辦 ， 去年 也 才 在 高雄 西子 灣辦過 ， 不 知道 為何 這次 會 造成 這麼 嚴重 的 意外 ； 但 警方 對 這樣 的 說法 保留 態度 。 而 士林 地檢署 今天 凌晨 也 已經 由 3 名檢察官 ， 連夜 到 八仙 樂園 了解 情況 ， 並 扣押 噴發 氣體 和 粉塵 的 鋼瓶 。 據 了解 ， 檢方 人員到 現場 後 發現 ， 舞台 設在 游泳池 中間 ， 其實 等 於 是 半密閉 空間 ， 而且 地上 四散 菸 蒂 和 打火 機 ， 不 排除 是 有人 不慎 點 菸 引燃 ， 造成 這次 的 意外 。 而 外界 關注 昨晚 現場 到底 有 沒 有 在 舞台 上 噴火 ， 據 了解 ， 昨晚 器材 中並 沒有 火焰 效果器 ， 檢警 初步 研判 ， 辦 趴用 的 粉彩 主要 成分 為 玉米粉 ， 在 一定 的 空間 、 一定 的 濃度 ， 遇到 靜電 或 火花 ， 不用 高溫 就 很 容易 引發 閃燃 現象 ，   可能 是 大量 接觸 熱能 ， 像是 舞台 光源 、 器材 電流 、 點 菸 等 引發 爆炸 ， 但 詳細 起火 原因 和 起火 點 ， 還是 要 經由 火場 鑑識 釐 清 。 檢警 近期 將陸續 傳喚 傷

In [98]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [99]:
X

<147x12829 sparse matrix of type '<class 'numpy.int64'>'
	with 23783 stored elements in Compressed Sparse Row format>

In [100]:
cs = cosine_similarity(X)

In [101]:
km = KMeans(n_clusters=4, init='k-means++', random_state=42)
c = km.fit_predict(cs)

In [102]:
c

array([0, 0, 3, 1, 0, 1, 0, 1, 1, 1, 1, 0, 3, 2, 2, 1, 0, 1, 1, 1, 2, 0,
       1, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 0, 3, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 3, 1, 3, 1, 1, 0,
       0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       2, 2, 0, 0, 3, 1, 2, 0, 0, 2, 0, 2, 1, 0, 2, 2, 2, 0, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2])

In [117]:
np_titles = np.array(titles)
np_titles

array(['八仙塵爆  五相關人依公共危險重傷害法辦', '八仙樂園意外 病患持續增加中', '希臘國內三分一自動櫃員機現金短缺',
       '台鐵新基隆車站29日正式啟用', '6月28日各報頭版要聞', '基改不算真食物  法國人知情就不買',
       '八仙樂園舞台大火 逾400人輕重傷', '女子世界盃足球賽  日擊敗澳洲晉4強', '《農民曆小幫手》國曆六月二十八日',
       '江蕙得「特別貢獻獎」 感恩金曲肯定她', '大台北今高溫上探37度', '八仙樂園意外 毛揆取消視察臺東行程',
       '歐元區財長拒希臘延長救助計劃', '羅志祥哭了 蔡依林讚表現很好', '蔡依林淚奪金曲 錦榮傳訊恭喜',
       '風評：陷入獵巫遊戲的中資認定', '八仙樂園貼出暫停營業海報', '挪威「行動大雕」出沒 隨機射路人',
       '還是熱！西半部高溫達37度', '德國即將關閉使用最久核子反應爐', '陳奕迅、張惠妹稱王封后  蔡依林抱回最大獎',
       '八仙樂園爆炸案 專家認玉米粉危險性高應管制使用', '張娟芬專文：抽絲剝繭邱和順案', '2015空姐夏裝大盤點',
       '呂紹煒專欄：違約與退出 希臘與歐洲才能重生(上)', '八仙樂園粉塵燃爆 400人傷 負責人被移送',
       '觀點投書：讀中文系的人，應該反對課綱微調', '觀點投書：何謂新兵訓練', '觀點投書：災難中的護理人',
       '呂政璋觀點：點土成金新思維~以台灣柳丁為例', '觀點投書：招搖的進步', '中俄美競造5音速機彈',
       '手相看什麼樣的女人性格強勢', '面相看哪些人財運綿長不盡', '【美洲盃八強】巴西 VS. 巴拉圭 線上直播！',
       '塔羅占卜你今生最看重的是什麼', '蘇塞大屠殺 凶手畫面曝光', '希臘違約在即  歐盟全力穩定經濟',
       '陳奕迅、莫文蔚伴侶均不知阿娜答金曲獲獎', '希臘脫歐變可能 歐洲衝擊大', '塔羅占卜你是個有心機的人嗎？',
       '八仙案  新店慈濟4傷者危急', '希債協議  法國願盡最後斡旋努力', '挑選新鮮食物 大有學問', '調心養心 初夏多吃蔬果',
       '夏天吃什麼好 紅棗、苦瓜攏總來', '補

**Based on Instructor Slides**

In [85]:
import pandas as pd
import re
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
import numpy as np

In [84]:
news100 = pd.read_excel('appledaily_politinews100.xlsx')
news100.head()

category                                            content  \
0       政治  總統蔡英文卸任民進黨主席，昨在臉書po給黨員的一封信，信中說，民進黨會展開一場轟轟烈烈的檢討...   
1       政治  民進黨這次九合一選舉慘敗，蔡英文辭去黨主席一職，昨公布「給黨員的一封信」，內容提到，最該改變...   
2       政治  2018年地方選舉國民黨拿下空前勝利，執政地區從6縣市竄升為15縣市，昨中常會上國民黨提出選...   
3       政治  準高雄市長韓國瑜的愛女韓冰昨(28日)受邀上政論節目《54新觀點》，首度與民進黨台北市議員王...   
4       政治                             點我直接觀看 被操弄的民調？《蘋果》數據解密   

                          title  
0    蔡英文要轟轟烈烈檢討民進黨　林濁水酸：民主國家沒聽過  
1      他列民進黨10大豬隊友　「不下架將賠上2020」  
2   選戰檢討報告出爐　國民黨：落選者「缺乏對外拓票企圖心」  
3  不用跳愛河！韓冰邀替高雄拚觀光　王世堅靦腆：可以廢物利用  
4      【民調解密3】林佳龍敗在紫爆　盧秀燕跌破眼鏡大勝

In [110]:
# 選擇文章，把文章分成句子
docNum = 31
testDoc = news100['content'][docNum]
testTitle = news100['title'][docNum]

def splitSentences(document):
    #for sent in re.findall(u'[^!?。\.\!\?]+[!?。\.\!\?]?', paragraph, flags=re.U):
    for sent in re.findall(u'[^!?。\!\?]+[!?。\!\?]?', document, flags=re.U):
        yield sent

sentenceDoc = []
for sent in list(splitSentences(testDoc))[:-1]:
    sentenceDoc.append(' '.join(jieba.cut(sent)))

# 原本文章
sentenceDoc

['今年 九 合一 大選 投票 狀況 多 ， 據 了解 ， 中選會 官方 網站 在 投票 日當天 曾 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊 ， 所幸 在 負責 網路 維護 中華電信 應變 下 ， 未進 一步 造成 影響 。',
 '中選會 副 主委 陳 朝 建今 證實 曾 遭駭客 攻擊 ， 不過 計票 網路 是 封閉 系統 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 因此 沒有 任何 影響 ， 境外 網路 干擾 也 並未 影響 投票 進程 。',
 '行政院 發言人 Kolas   Yotaka （ 谷辣斯 ・ 尤達卡 ） 表示 ， 中選會 在 選前 即 做好 縝密 防護 ， 因此 成功 防堵 攻擊 ， 接下 來 將針 對 有形 的 選務如 投票 排隊 問題 ， 以及 無形 的 選務 如資 安防 護進行 檢討 。',
 '不過 ， 投票 日當天 開票 進程 緩慢 ， 台北市 選情 更 創下史 上 第一次 開票 長 達 9 小時 的 紀錄 ， 陳 朝建 說明 ， 開票 時間 長 是 因為 投票 時間 延 後 ， 計票 不受 駭客 影響 ， 開票 也 自然 不受 此 影響 。',
 '據 內部 消息 指出 ， 投票 日當天 曾 出現 從 境外 進行 分散式 阻斷 服務 （ DDoS ） 攻擊 ， 企圖 癱瘓 中選會 網站 ， 不過 在 中華電信 、 中選會 緊急 處理 後 ， 阻斷 來 自國外 異常 流量 ， 在 短 時間 獲得 解決 ， 一般 民眾 並沒有 發現 特殊 異樣 。',
 'NCC 及 中華電信 暫未 對 此 做 進 一步 說明 。',
 '陳 朝建 表示 ， 受 攻擊 的 是 中 選會 官方 網站 ， 當日 開票 的 計票 網路 是 獨立 的 封閉 網路 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 完全 未有 任何 影響 ； 中華電信 團隊 也 是 24 小時 監控 與 防護 作業 ， 也 沒 有 受到 任何 影響 。',
 '陳 朝建 說 ， 受到 攻擊 的 官網 ， 當日 皆 有 隨時 防衛 ， 中華電信 團隊 24 小時 監控 與 防護 作業 ； 故當 日 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊時 ， 在 負責 網路 維護 中華電信 的 緊急 應變 下 ， 並

In [111]:
vect = CountVectorizer()
X = vect.fit_transform(sentenceDoc)
word = vect.get_feature_names()

In [112]:
n_cosine_similarities = cosine_similarity(X)
n_cosine_similarities

array([[1.        , 0.29032258, 0.13116517, 0.18146655, 0.37387825,
        0.16064387, 0.23308662, 0.44901326, 0.18247917, 0.17255919],
       [0.29032258, 1.        , 0.13116517, 0.23331413, 0.17255919,
        0.        , 0.52444489, 0.1796053 , 0.27371875, 0.0862796 ],
       [0.13116517, 0.13116517, 1.        , 0.05270463, 0.11694107,
        0.        , 0.08885233, 0.06085806, 0.34780417, 0.46776428],
       [0.18146655, 0.23331413, 0.05270463, 1.        , 0.13867505,
        0.06454972, 0.2575611 , 0.09622504, 0.        , 0.04622502],
       [0.37387825, 0.17255919, 0.11694107, 0.13867505, 1.        ,
        0.07161149, 0.07792865, 0.26688026, 0.18302666, 0.17948718],
       [0.16064387, 0.        , 0.        , 0.06454972, 0.07161149,
        1.        , 0.07254763, 0.1490712 , 0.        , 0.        ],
       [0.23308662, 0.52444489, 0.08885233, 0.2575611 , 0.07792865,
        0.07254763, 1.        , 0.45962736, 0.22662355, 0.05195243],
       [0.44901326, 0.1796053 , 0.0608580

In [113]:
km = KMeans(n_clusters=3, init='k-means++')
c = km.fit_predict(n_cosine_similarities)

In [115]:
c

array([0, 2, 1, 2, 0, 0, 2, 0, 1, 1])

In [120]:
np_doc = np.array(sentenceDoc)
np_doc[c==0]

array(['今年 九 合一 大選 投票 狀況 多 ， 據 了解 ， 中選會 官方 網站 在 投票 日當天 曾 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊 ， 所幸 在 負責 網路 維護 中華電信 應變 下 ， 未進 一步 造成 影響 。',
       '據 內部 消息 指出 ， 投票 日當天 曾 出現 從 境外 進行 分散式 阻斷 服務 （ DDoS ） 攻擊 ， 企圖 癱瘓 中選會 網站 ， 不過 在 中華電信 、 中選會 緊急 處理 後 ， 阻斷 來 自國外 異常 流量 ， 在 短 時間 獲得 解決 ， 一般 民眾 並沒有 發現 特殊 異樣 。',
       'NCC 及 中華電信 暫未 對 此 做 進 一步 說明 。',
       '陳 朝建 說 ， 受到 攻擊 的 官網 ， 當日 皆 有 隨時 防衛 ， 中華電信 團隊 24 小時 監控 與 防護 作業 ； 故當 日 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊時 ， 在 負責 網路 維護 中華電信 的 緊急 應變 下 ， 並沒有 受到 影響 。'],
      dtype='<U203')

In [122]:
sentenceDoc

['今年 九 合一 大選 投票 狀況 多 ， 據 了解 ， 中選會 官方 網站 在 投票 日當天 曾 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊 ， 所幸 在 負責 網路 維護 中華電信 應變 下 ， 未進 一步 造成 影響 。',
 '中選會 副 主委 陳 朝 建今 證實 曾 遭駭客 攻擊 ， 不過 計票 網路 是 封閉 系統 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 因此 沒有 任何 影響 ， 境外 網路 干擾 也 並未 影響 投票 進程 。',
 '行政院 發言人 Kolas   Yotaka （ 谷辣斯 ・ 尤達卡 ） 表示 ， 中選會 在 選前 即 做好 縝密 防護 ， 因此 成功 防堵 攻擊 ， 接下 來 將針 對 有形 的 選務如 投票 排隊 問題 ， 以及 無形 的 選務 如資 安防 護進行 檢討 。',
 '不過 ， 投票 日當天 開票 進程 緩慢 ， 台北市 選情 更 創下史 上 第一次 開票 長 達 9 小時 的 紀錄 ， 陳 朝建 說明 ， 開票 時間 長 是 因為 投票 時間 延 後 ， 計票 不受 駭客 影響 ， 開票 也 自然 不受 此 影響 。',
 '據 內部 消息 指出 ， 投票 日當天 曾 出現 從 境外 進行 分散式 阻斷 服務 （ DDoS ） 攻擊 ， 企圖 癱瘓 中選會 網站 ， 不過 在 中華電信 、 中選會 緊急 處理 後 ， 阻斷 來 自國外 異常 流量 ， 在 短 時間 獲得 解決 ， 一般 民眾 並沒有 發現 特殊 異樣 。',
 'NCC 及 中華電信 暫未 對 此 做 進 一步 說明 。',
 '陳 朝建 表示 ， 受 攻擊 的 是 中 選會 官方 網站 ， 當日 開票 的 計票 網路 是 獨立 的 封閉 網路 ， 並 非公 開網 路 ， 無法 由 外界 接取 ， 完全 未有 任何 影響 ； 中華電信 團隊 也 是 24 小時 監控 與 防護 作業 ， 也 沒 有 受到 任何 影響 。',
 '陳 朝建 說 ， 受到 攻擊 的 官網 ， 當日 皆 有 隨時 防衛 ， 中華電信 團隊 24 小時 監控 與 防護 作業 ； 故當 日 遭到 來 自 境外 大規模 分散式 阻斷 服務 （ DD0oS ） 攻擊時 ， 在 負責 網路 維護 中華電信 的 緊急 應變 下 ， 並